### ISSUE TITLE
Add screenshots of game to README.md

### ISSUE THREAD

**Issue by jamesgiu** [ChrisNeedham24/microcosm#67]
Show off how cool the game looks. Good first issue I suppose

**Comment by Bhavyaseth-afk** [comment]
Please see if this could be assigned to me
I would like to contribute

**Comment by ChrisNeedham24** [comment]
Hi @Bhavyaseth-afk sorry about that, feel free to start on this.

**Comment by ChrisNeedham24** [comment]
Hey, how are you going with this one, @Bhavyaseth-afk? I've received some interest from others on doing this issue, so I thought it would be best to check in.

**Comment by ChrisNeedham24** [comment]
Since it's been a couple of weeks without activity, I'll reassign this one.

**Comment by Money-20** [comment]
I anyone's not working on this issue I wish to contritbute.

**Comment by jamesgiu** [comment]
Fantastic screenshots

**Comment by jamesgiu** [comment]
@langstof825 saves the day
