### ISSUE TITLE
Add terrain-based attacks

### ISSUE THREAD

**Issue by ChrisNeedham24** [ChrisNeedham24/microcosm#72]
There should probably be some advantage for units that are attacking from mountains, and a disadvantage for defending from the sea. Open to ideas on how this should work.
Credit: @jamesgiu and Andrew

**Comment by jamesgiu** [comment]
Thoughts on extending this by adding in support mechanics (e.g. additional power if a friendly unit is in an adjacent quad etc)?

**Comment by ChrisNeedham24** [comment]
At this stage, I'd probably prefer to keep the combat fairly simple. However, by the time this issue gets done, who knows? Maybe that sort of thing will be on the cards.

**Comment by ChrisNeedham24** [comment]
Having certain factions be better on certain terrain types was also discussed for this, would definitely be interesting.

**Comment by ChrisNeedham24** [comment]
I think at this point adding this sort of advantage/disadvantage to factions probably creates an imbalance and doing the same with quads creates a difference between biomes in a physical sense where previously it's just the stats that are different. It's not like you actually sail across the sea quads.

**Comment by ChrisNeedham24** [comment]
My view on this hasn't changed since the last comment, so I think we can close this for the time being.
