### ISSUE TITLE
Shorten maximum night length

### ISSUE THREAD

**Issue by ChrisNeedham24** [ChrisNeedham24/microcosm#78]
Currently nights last for a random number between 5 and 25 turns. If you are doing a lot on your turn, this can result in a long time between climatic changes.

**Acceptance Criteria:**
- Reduce the maximum night length from 25 to 20 turns.

**Comment by Abdirizaks12** [comment]
assign me please

**Comment by sculley** [comment]
Hello, please assign this to me. I have submitted PR #80 to address this. Thanks
