### ISSUE TITLE
Refactor menu.py

### ISSUE THREAD

**Issue by ChrisNeedham24** [ChrisNeedham24/microcosm#85]
This one might be a little more complicated. To begin with, the display functionality can be extracted out, but then also divided up potentially.

**Comment by jasonlwj** [comment]
👀 I've already started cheeky work on my own branch for this file

**Comment by ChrisNeedham24** [comment]
Refactoring as cheeky work :TrollDespair:

**Comment by jasonlwj** [comment]
Everything is cheeky work

**Comment by ChrisNeedham24** [comment]
There will probably be some fairly significant merge conflicts on this now due to #89. Apologies for that 😬

**Comment by jasonlwj** [comment]
How bad could it be 
![Clueless](https://user-images.githubusercontent.com/8891030/195331878-76614d72-8141-482e-b55a-3baf47fbd33e.png)

**Comment by ChrisNeedham24** [comment]
![image](https://user-images.githubusercontent.com/20379984/195577782-9a42a204-613c-4147-8a3d-4b2cea99f121.png)

**Comment by jasonlwj** [comment]
I'm gonna open up the PR for now - my work is far from done but maybe the current changes can be merged in for now. Then I can continue working on a refactor part 2 (hell yeah it's happening)

**Comment by ChrisNeedham24** [comment]
Sounds good, I'll have a look. I won't make that PR close this issue, hopefully your part 2 will do that 👀
