### ISSUE TITLE
Add Ctrl + arrow keys to control menu

### ISSUE THREAD

**Issue by Kurtsley** [ChrisNeedham24/microcosm#87]
Need to add an entry for the Ctrl + arrow keys to fast pan the map. Would like input on the exact wording. I was thinking either:

CTRL + ARROWS       Fast scroll the map
or
HOLD CTRL         Fast scroll the map

For some reason scroll sounds better than pan even though it doesn't make as much sense. Thoughts?

**Comment by ChrisNeedham24** [comment]
I think of those options CTRL + ARROWS is better. Not sure about scroll vs pan, though. Might ask around and gather some opinions.

**Comment by mushahidq** [comment]
Hi! I'd like to contribute to the repo. Is this issue a good place to start?

**Comment by Kurtsley** [comment]
Go ahead, overlay_display.py is the file to you want to look at.

**Comment by mushahidq** [comment]
Thanks! Does this look good?
![image](https://user-images.githubusercontent.com/25764880/194741371-e7884bbc-8166-4e3b-bb04-a223362ace1c.png)

**Comment by ChrisNeedham24** [comment]
Looks great! We'll still need to standardise between pan and scroll, though, so at least one more change will be needed.

**Comment by Kurtsley** [comment]
I know of at least one more key that will needed to be added to this menu, the M key. Since it is getting crowded, either the Ctrl + arrows should be fit into one line or the menu could be extended vertically. Maybe need a separate issue for this.

**Comment by ChrisNeedham24** [comment]
That's a good point, @Kurtsley. I think then maybe a better idea for this one would be to fit it onto one line, and then move the descriptions a little to the right. I've also talked with a few people about pan vs scroll, and we generally agreed that pan is a better descriptor because scrolling seems to suggest up and down only.

Fast pan does sound a bit odd, though, so how about `Quickly pan the map`, @mushahidq?

**Comment by ChrisNeedham24** [comment]
Looking great! Perhaps the text could all be moved over slightly so that the empty space is equal on each side, though?

**Comment by ChrisNeedham24** [comment]
There may be some minor merge conflicts for this now due to #89. Hopefully nothing too major.
