### ISSUE TITLE
Handle cases where loaded save files are no longer valid

### ISSUE THREAD

**Issue by ChrisNeedham24** [ChrisNeedham24/microcosm#94]
For example, if an attribute has been changed in one of the models, an old save file will no longer work, and will crash the app.

The easiest way to do this is probably catch all Exceptions from the `load_game()` method, and display some kind of warning that the save file is not valid. Potentially also encourage the user to download an older release of the game if they want to use that file.

**Comment by langstof825** [comment]
I can start looking into this.

**Comment by langstof825** [comment]
So is it acceptable to then just catch the generic Exception and provide a warning message? Or do we want to catch and handle the different exceptions? Like AttributeError for example. I have currently got it so that it just catches the generic Exception.

**Comment by ChrisNeedham24** [comment]
I think just catching the generic Exception is fine. Btw if you choose not to do the backward compatibility thing, it'd be great if you could make another issue for that when you put up the PR.

**Comment by langstof825** [comment]
Created new issue MCR-103 to address backwards compatibility.
