### ISSUE TITLE
Rename the sieging field of the Unit object to besieging

### ISSUE THREAD

**Issue by ChrisNeedham24** [ChrisNeedham24/microcosm#95]
Make sure to update any documentation that refers to 'sieging' as well; you should be able to search for the string `sieging` in the project and find no results that aren't `besieging`.

**Comment by VishMaster17** [comment]
Hi @ChrisNeedham24 , can you please assign this to me.

**Comment by ChrisNeedham24** [comment]
Sure, @VishMaster17.
